fix: reject and requeue double acknowledgement
ruby-amqp/hutch pull request #388
Opened 2022-12-03 14:56 UTC by ahmedsaalah

Fix Issue in (requeue! and reject! )
For Example:
When you are using reject!
1. Will broker.reject(delivery_info.delivery_tag) -> will go to def reject in broker.rb
2. Will call channel.reject(delivery_tag, false)-> will go to bunny reject in channel.rb
3. Will call  basic_reject(delivery_tag.to_i, false) which going to reject the message So it's acknowledged
4. In worker.rb handle_message by default do  @broker.ack(delivery_info.delivery_tag) so it's going to be double acknowledged
Solution : 

1. Add Boolean in reject and requeue in broker.rb that message rejected
2. in handle_message before doing default ack check on this boolean

2022-12-04 17:04 UTC, michaelklishin commented
Should this new ivar be reset at some point?

2022-12-04 18:12 UTC, ahmedsaalah commented
https://github.com/ruby-amqp/hutch/blob/87adff64c8c43fa4ec15b258b851d81d12968e15/lib/hutch/worker.rb#L72
In worker.rb handle_message method, every message consumer_instance instantiated so no need to be reset at all
`      consumer_instance = consumer.new.tap { |c| c.broker, c.delivery_info = @broker, delivery_info }
`

2022-12-07 14:15 UTC, ahmedsaalah commented
> Should this new ivar be reset at some point?

@michaelklishin Please let me know if you have any other concerns

2022-12-07 19:35 UTC, michaelklishin requested changes
These two tests need updating:

```
Failures:

  1) Hutch::Worker#handle_message acknowledges the message
     Failure/Error: @broker.ack(delivery_info.delivery_tag) unless consumer_instance.message_rejected?
       #<Double "Consumer instance"> received unexpected message :message_rejected? with (no args)
     # ./lib/hutch/worker.rb:74:in `handle_message'
     # ./spec/hutch/worker_spec.rb:92:in `block (3 levels) in <top (required)>'

  2) Hutch::Worker#handle_message passes the message to the consumer
     Failure/Error: @broker.ack(delivery_info.delivery_tag) unless consumer_instance.message_rejected?
       #<Double "Consumer instance"> received unexpected message :message_rejected? with (no args)
     # ./lib/hutch/worker.rb:74:in `handle_message'
     # ./spec/hutch/worker_spec.rb:86:in `block (3 levels) in <top (required)>'

Finished in 15.29 seconds (files took 11.03 seconds to load)
141 examples, 2 failures

Failed examples:

rspec ./spec/hutch/worker_spec.rb:89 # Hutch::Worker#handle_message acknowledges the message
rspec ./spec/hutch/worker_spec.rb:83 # Hutch::Worker#handle_message passes the message to the consumer
```

2022-12-20 10:36 UTC, ahmedsaalah commented
@michaelklishin Hello, Could you please send for me if there is any issue? Thanks in advance

2022-12-20 19:49 UTC, merged